<?php 
$consume = array_map(null, isset($this->chartBank['data']) ? $this->chartBank['data'] : array(), isset($this->chart['data']) ? $this->chart['data'] : array());

$this->headScript()->appendFile($this->baseUrl('/scripts/RGraph/RGraph.line.js'));
$this->headScript()->appendFile($this->baseUrl('/scripts/RGraph/RGraph.bar.js'));
$this->headScript()->captureStart();
?>
$(function() {
	var consume = new RGraph.Bar('chart', $.map(<?php echo Zend_Json::encode(isset($consume) ? $consume : array()) ?>, function(v) { return [[v[0]/10000 + 0, v[1]/10000 + 0]] }));
		consume.Set('chart.background.grid.autofit', true);
		consume.Set('chart.gutter.left', 50);
		consume.Set('chart.gutter.right', 40);
		consume.Set('chart.gutter.bottom', 100);
		consume.Set('chart.colors', ['#4E81BA', '#FF0000']);
		consume.Set('chart.key', ['网银消耗点数(单位：万)', '消耗点数(单位：万)']);
		consume.Set('chart.key.background', 'white');
		consume.Set('chart.key.position', 'gutter');
		consume.Set('chart.key.position.x', 100);
		consume.Set('chart.key.position.y', 230);
		consume.Set('chart.key.position.gutter.boxed', false);
		consume.Set('chart.labels', <?php echo $this->labelFormat(isset($this->chart['label']) ? $this->chart['label'] : array()) ?>);
		consume.Set('chart.text.font', 'tahoma, arial, 宋体');
	
	var pecentage = new RGraph.Line('chart', <?php echo Zend_Json::encode(array_map(function($netbank, $consume) { return @round($netbank / $consume * 100, 2); }, isset($this->chartBank['data']) ? $this->chartBank['data'] : array(), isset($this->chart['data']) ? $this->chart['data'] : array())) ?>);
		pecentage.Set('chart.background.grid', false);
		pecentage.Set('chart.linewidth', 2);
		pecentage.Set('chart.tickmarks', 'endcircle');
		pecentage.Set('chart.colors', ['#A3AE6A']);
		pecentage.Set('chart.key', ['网银消耗比例']);
		pecentage.Set('chart.key.background', 'white');
        pecentage.Set('chart.key.position', 'gutter');
		pecentage.Set('chart.key.position.x', 430);
		pecentage.Set('chart.key.position.y', 230);
		pecentage.Set('chart.key.position.gutter.boxed', false);
		pecentage.Set('chart.gutter.left', 50);
		pecentage.Set('chart.gutter.right', 40);
		pecentage.Set('chart.gutter.bottom', 80);
		pecentage.Set('chart.hmargin', 10);
		pecentage.Set('chart.text.font', 'tahoma, arial, 宋体');

 	var combo = new RGraph.CombinedChart(consume, pecentage);
    combo.Draw();
    
    	pecentage.Set('chart.noaxes', false);
		pecentage.Set('chart.noxaxis', true);
		pecentage.Set('chart.yaxispos', 'right');
		pecentage.Set('chart.ymax', 100);
		pecentage.Set('chart.ylabels', true);
		pecentage.Set('chart.units.post', '%');
		
	RGraph.RedrawCanvas(pecentage.canvas);
});
<?php 
$this->headScript()->captureEnd();
?>
		<canvas id="chart" width="740" height="300" style="background-color: white;">
        	[IE7+ is required to view the charts.]
        </canvas>
