
        	<div class="defBar_left"></div>
            <div class="defBar_middle">
            	<span class="title"><?php echo $this->navigation()->mvcMenu()->renderCurrentMenu() ?></span>
                <span class="right">
                    <span class="btn3">实时监控</span>
                </span>
            </div>
            <div class="defBar_right"></div>
            
            <div class="main_div">
                <div class="kpi_chos_time_div">
                	<div class="top_bar">
                    	<span class="title">（<?php echo $this->deadline($this->start), '～', $this->deadline($this->end) ?>）</span>
                        <span class="right">
                            <span class="btn8">下载报表</span>
                        </span>
                    </div>
                    <div class="txt_main_div">
                    	<div class="d1">请选择你要查看的时间段：</div>
                        <div>
                        	<?php echo $this->partial('formdate.phtml', 
                        				array('dates' => array(
                        						ZtChart_Model_Assemble_Datetime::TODAY, 
                        						ZtChart_Model_Assemble_Datetime::YESTODAY, 
                        						ZtChart_Model_Assemble_Datetime::RECENT_1WEEK, 
                        						ZtChart_Model_Assemble_Datetime::RECENT_1MONTH, 
                        						ZtChart_Model_Assemble_Datetime::CUSTOM
                        					)
                        				)); 
                        	?>
                        </div>
                    </div>
                </div>
          		<?php if (!empty($this->chart)) {?>
                <div class="iframe_div">
                	<iframe scrolling="no" frameborder="0" src="<?php echo $this->url(array('action' => 'period', 'controller' => 'online', 'chart' => 'bar')) ?>"></iframe>
                </div>
                <br />
            	<table align="center" cellpadding="0" cellspacing="1" width="740" class="mainTable">
                	<tr class="t_tr">
                        <td>时段</td>
                        <td><a href="<?php echo $this->baseUrl('/help#b5') ?>" target="_blank" title="最高同时在线人数">PCU</a></td>
                        <td><a href="<?php echo $this->baseUrl('/help#b4') ?>" target="_blank" title="平均同时在线人数">ACU</a></td>
                    </tr>
                    <?php
                    foreach ($this->chart as $label => $chart) {
                    ?>
                    <tr class="<?php echo $this->cycle(array('d_tr_1', 'd_tr_2'))->next() ?>">
                        <td><?php echo $label ?></td>
                        <td><?php echo $chart['data'] ?></td>
                        <td><?php echo $chart['apa'] ?></td>
                        <td><?php echo @round($chart['data'] / $chart['apa'], 2) ?></td>
                    </tr>
                    <?php
                    } 
                    ?>  
                </table>
                <?php } ?>
            </div>