<?php 
$this->headScript()->appendFile($this->baseUrl('/scripts/RGraph/RGraph.bar.js'));
$this->headScript()->captureStart();
?>
$(function() {
	RGraph.Clear(document.getElementById('chart'));
	var chart = new RGraph.Bar('chart', 
    					$.map(<?php echo Zend_Json::encode(isset($this->chart['data']) ? $this->chart['data'] : array()) ?>, function(v) { return v + 0 }));
    	chart.Set('chart.background.grid.autofit', true);
    	chart.Set('chart.gutter.left', 60);
    	chart.Set('chart.gutter.right', 20);
    	chart.Set('chart.colors.sequential', true);
    	chart.Set('chart.colors', ['#afd8f8','#f6bd0f','#8bba00','#ff8e46','#008e8e','#d64646','#8e468e','#588526','#fff468','#008ed6','#9d080d','#a186be','#cc6600','#fdc689','#aba000','#f26d7d','#fff200','#0054a6','#f7941c','#cc3300','#006600','#663300','#afd8f8','#f6bd0f']);
    	chart.Set('chart.labels.above', true);
    	chart.Set('chart.labels', $.map(<?php echo Zend_Json::encode(isset($this->chart['label']) ? $this->chart['label'] : array()) ?>, function(v) { return v.substr(-1) % 2 == 0 ? v.substr(11) : '' }));
    	chart.Set('chart.text.color', '#333');
		chart.Set('chart.text.font', 'tahoma, arial, 宋体');
	
	chart.Draw();
});
<?php 
$this->headScript()->captureEnd() 
?>		
		<canvas id="chart" width="740" height="230" style="background-color: white;">
        	[IE7+ is required to view the charts.]
        </canvas>