		<form method="post">
			<ul>
	        	<li>
	            	<span class="spanTxt">标题：</span>
	                <input name="notice_title" type="text" class="textInput"/>
	            </li>
	            <li class="heiAuto">
	            	<span class="spanTxt">正文：</span>
	                <textarea name="notice_content"></textarea>
	            </li>
	     
	            <li class="liTxtCenter">
	            	<input type="hidden" name="notice_datetime" value="<?php echo date('Y-m-d H:i:s') ?>" />
	            	<button class="btn2" type="submit">确定</button>
	                <button class="btn2" type="button">取消</button>
	            </li>
			</ul>
		</form>