<?php 
$this->headTitle('意见管理');
$this->headScript()->captureStart(); 
?>
$(function(){
	$('.dialog').click(function(e) {
		e.preventDefault();
		$('<iframe src="' + this.href + '"></iframe>').dialog(
			{
				'width': 500, 
				'resizable': false, 
				'title': $(this).text(), 
				'open': function() {
					this.style.width = '95%';
				}
			}
		);
	});
});
<?php
$this->headScript()->captureEnd(); 
?>
			<div class="defBar_left"></div>
            <div class="defBar_middle">
            	<span class="title">意见管理</span>
                <span class="right">
                    <?php echo $this->navigation()->mvcMenu()->renderMVCMenu('search', null, null, array('format' => 'inbox'), array('class' => 'btn3 dialog')) ?>
                </span>
            </div>
            <div class="defBar_right"></div>
            
            <div class="main_div">
            	<table align="center" cellpadding="0" cellspacing="1" width="740" class="mainTable">
                	<tr class="t_tr">
                    	<td>意见ID</td>
                        <td>提交时间</td>
                        <td>提交人</td>
                        <td>标题</td>
                        <td>类型</td>
                        <td>状态</td>
                        <td>答复时间</td>
                        <td>答复人</td>
                        <td></td>
                    </tr>
                    <?php foreach ($this->paginator->getCurrentItems() as $opinion) { ?>
                    <tr class="<?php echo $this->cycle(array('d_tr_1', 'd_tr_2'))->next() ?>">
                    	<td><?php echo $opinion['opinion_id'] ?></td>
                        <td><?php echo $opinion['opinion_submit_datetime'] ?></td>
                        <td><?php echo $opinion['opinion_submitter'] ?></td>
                        <td><?php echo $opinion['opinion_title'] ?></td>
                        <td><?php echo $opinion['opinion_category'] ?></td>
                        <td><?php echo $opinion['opinion_status'] ? '已解决' : '新建' ?></td>
                        <td><?php echo $opinion['opinion_reply_datetime'] ?></td>
                        <td><?php echo $opinion['opinion_replier'] ?></td>
                        <td><?php echo $this->navigation()->mvcMenu()->renderMVCMenu('reply', null, null, array('format' => 'inbox', 'opinion_id' => $opinion['opinion_id']), array('class' => 'btn2 dialog')) ?></td>
                    </tr>
                    <?php 
					}
					for ($i = 0; $i < (Zend_Paginator::getDefaultItemCountPerPage() - $this->paginator->getCurrentItemCount()); $i++) {
                    ?>
                    <tr class="<?php echo $this->cycle(array('d_tr_1', 'd_tr_2'))->next() ?>">
                    	<td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <?php
                    } 
                    ?>
                </table>
                <div class="page_div"><?php echo $this->paginationControl() ?></div>
            </div>