
       <form method="post">
			<ul>
	        	<li>
	            	<span class="spanTxt">提交人：</span>
	                <?php echo $this->opinion['opinion_submitter'] ?>
	            </li>
	            <li>
	            	<span class="spanTxt">标题：</span>
	                <?php echo $this->opinion['opinion_title'] ?>
	            </li>
	            <li style="height:auto;">
	            	<span class="spanTxt">内容：</span>
	            	<span class="sys_opinion_content"><?php echo $this->opinion['opinion_content'] ?></span>
	            </li>
	            <?php if (!empty($this->opinion['opinion_attachment'])) { ?>
	 			<li>
	            	<span class="spanTxt">附件：</span>
	               	<?php echo substr(strstr($this->opinion['opinion_attachment'], '_'), 1) ?>
	               	<a href="?download">下载</a>
	            </li>
	            <?php } ?>
	            <li style="height: 120px;">
	            	<span class="spanTxt">答复内容：</span>
	            	<textarea name="opinion_reply"></textarea>
	            </li>
	            <li class="liTxtCenter">
	            	<input type="hidden" name="opinion_replier" value="<?php echo $this->auth() ?>" />
	            	<input type="hidden" name="opinion_reply_datetime" value="<?php echo date('Y-m-d H:i:s') ?>" />
	            	<button type="submit" class="btn2">确定</button>
	                <button type="button" class="btn2">取消</button>
	            </li>
	       </ul>
       </form>