<!DOCTYPE html >
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="text/javascript" src="<?php echo $this->baseUrl('/scripts/jquery-1.7.1.min.js')?>"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl('/scripts/RGraph/RGraph.common.core.js')?>"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl('/scripts/RGraph/RGraph.line.js')?>"></script>
	<script type="text/javascript">
		$(function() {
	    	chart = new RGraph.Line('chart', <?php echo Zend_Json::encode($this->chart['data']) ?>);
	    	chart.Set('chart.background.grid.autofit', true);
	    	chart.Set('chart.gutter.left', 35);
	    	chart.Set('chart.gutter.right', 5);
	    	chart.Set('chart.hmargin', 10);
	    	chart.Set('chart.labels.above', true);
	    	chart.Set('chart.tickmarks', 'endcircle');
	    	chart.Set('chart.labels', <?php echo Zend_Json::encode($this->chart['label']) ?>);
	    	chart.Set('chart.text.angle', 45);
	    	chart.Set('chart.text.size', 8);
	    	chart.Draw();
		});
	</script>
	<title>ZtChart Demo - Line</title>
</head>
<body>
	<canvas id="chart" width="1200" height="500">[No canvas support]</canvas>
</body>
</html>
