<?php 
$data = array_merge(array_slice($this->chart['data'], 0, 7), (array) array_sum(array_slice($this->chart['data'], 5)));
$label = array_merge(array_slice($this->chart['label'], 0, 7), (array) ZtChart_Model_Assemble_Area::OTHER);
array_walk($label, function(&$value, $key) use ($data) { 
	$pecentage = @round($data[$key] / array_sum($data) * 100, 2);
	$value = ZtChart_Model_Assemble_Area::getAreaChineseName($value) . "({$pecentage}%)"; 
});
$this->headScript()->appendFile($this->baseUrl('/scripts/RGraph/RGraph.pie.js'));
$this->headScript()->captureStart();
?>
$(function() {
		RGraph.Clear(document.getElementById('chart'));
    	var pie = new RGraph.Pie('chart', <?php echo Zend_Json::encode($data) ?>);
            pie.Set('chart.gutter.left',-100);
			pie.Set('chart.gutter.bottom', 45);
            pie.Set('chart.colors', ['red', 'pink', '#6f6', 'blue', 'yellow', 'green', 'maroon', 'olive']);
            pie.Set('chart.key', <?php echo Zend_Json::encode(array_values($label)) ?>);
            pie.Set('chart.key.background', 'white');
			pie.Set('chart.key.position.x', 210);
            pie.Set('chart.strokestyle', 'white');
            pie.Set('chart.linewidth', 3);
            pie.Set('chart.exploded', [3,3,3,3,3,3,3,3]);
            pie.Set('chart.shadow', true);
            pie.Set('chart.shadow.offsetx', 0);
            pie.Set('chart.shadow.offsety', 0);
            pie.Set('chart.shadow.blur', 25);
            
            pie.Draw();
});
<?php 
$this->headScript()->captureEnd() 
?>		
		<canvas id="chart" width="380" height="260" style="background-color: white;">
        	[IE7+ is required to view the charts.]
        </canvas>
