<?php 
$this->headTitle('角色管理');
?>
			<div class="defBar_left"></div>
            <div class="defBar_middle">
            	<span class="title"><?php echo $this->navigation()->mvcMenu()->renderCurrentMenu() ?></span>
            </div>
            <div class="defBar_right"></div>
            <div class="main_div">
            	<form method="post">
					<table align="center" cellpadding="0" cellspacing="0" style="background: none;">
						<tr>
							<td width="99" align="center"><strong>角色名称</strong></td>
							<td align="left"><input type="text" name="role_name" id="role_name" value="<?php echo $this->role['role_name'] ?>" /></td>
						</tr>
						<tr>
							<td width="99" align="center"><strong>角色描述</strong></td>
							<td align="left"><input type="text" name="role_desc" id="role_desc" value="<?php echo $this->role['role_desc'] ?>" /></td>
						</tr>
						<tr>
							<td width="99" align="center"><strong>游戏</strong></td>
							<td align="left">
								<?php echo $this->formMultiCheckbox('role_gametype[]', Zend_Json::decode($this->role['role_gametype']), null, $this->gameTypes, PHP_EOL) ?>
							</td>
						</tr>
						<tr>
							<td align="center" colspan="2">
								<button type="submit" class="btn2">修改</button>
								<button type="reset" class="btn2">重置</button>
							</td>
						</tr>
					</table>
				</form>
            </div>