<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <title>平台实时监控数据系统</title>
    
    <?php echo $this->headLink() ?>
    
    <script type="text/javascript" src="<?php echo $this->baseUrl('/scripts/jquery-1.7.1.min.js')?>"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl('/scripts/RGraph/RGraph.common.core.js')?>"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl('/scripts/RGraph/RGraph.common.dynamic.js')?>"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl('/scripts/RGraph/RGraph.common.effects.js')?>"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl('/scripts/RGraph/RGraph.common.tooltips.js')?>"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl('/scripts/RGraph/RGraph.common.key.js')?>"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl('/scripts/RGraph/RGraph.common.annotate.js')?>"></script>
    <?php echo $this->headScript() ?>
    
</head>
<body>
	<?php echo $this->layout()->content ?>

</body>
</html>
