<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?php echo $this->headMeta() ?>
		
	<?php $this->headTitle('平台实时监控数据系统', 'PREPEND')->setSeparator('-') ?>
    <?php echo $this->headTitle() ?>
    
    <?php 
    	$this->headLink()->prependStylesheet($this->baseUrl('/styles/index.css'));
    ?>
		
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    
    <?php echo $this->jQuery() ?>
    <script type="text/javascript">
    $(function(){
        $('iframe[src="' + location.href + '"]', parent.document).height($('body').height());
    });
	</script>
    <?php echo $this->headScript() ?>
</head>
<body>
	<?php echo $this->layout()->content ?>
    <?php echo $this->layout()->dialog ?>
</body>
</html>